server:
  port: 5000 # 端口号

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:10050/eureka
    registry-fetch-interval-seconds: 5 #间隔多久去拉取服务注册信息，默认为30秒
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,页面会显示主机名
    preferIpAddress: true     #访问路径可以显示IP地址




